New/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.base, name='base'),
]

mySite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('Index.urls')),
    path('Index/', include('Index.urls')),
    path("zapis/", include("zapis.urls", namespace="zapis")),
    path("accounts/", include("accounts.urls")),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

zapis/urls.py
from django.urls import path

from . import views

app_name = "zapis"

urlpatterns = [
    path("list/", views.zapis_by_tag, name="list"),
    path("list/tag/<slug:tag_slug>", views.zapis_by_tag, name="list_by_tag"),
    path("create/", views.ZapisCreateView.as_view(), name="create"),
    path("add-zapis/", views.add_zapis, name="api-add-zapis"),
    path("complete/<int:uid>", views.complete_zapis, name="complete"),
    path("delete/<int:uid>", views.delete_zapis, name="delete"),
    path("details/<int:pk>", views.ZapisDetailsView.as_view(), name="details"),
    path("edit/<int:pk>", views.ZapisEditView.as_view(), name="edit"),
    path("export/", views.ZapisExportView.as_view(), name="export"),
]

templates/home.html
{% load static %}
<html xmlns:zapis="http://www.w3.org/1999/xhtml" lang="">
  <head>
    <title>{% block title %}Туду-дуду{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <script src="http://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    {% block extra_head %}{% endblock %}
  </head>
  <body>
    <div class="container">
      <div class="row">

        <div class="side_bar col">
          {% block side_bar %}
            {% if user.is_authenticated %}
              <p>{{ user.first_name }}</p>
              <p>Login: {{ user.username }}</p>

              <ul>

                <li><i class="fa fa-plus"></i>&nbsp;<a href="{% url "zapis:create" %}">Сделать запись</a></li>
                <li><i class="fas fa-clipboard-list"></i>&nbsp;<a href="{% url "zapis:list" %}">Записи</a></li>
                <li><i class="fa fa-sign-out-alt"></i>&nbsp;<a href="{% url "logout" %}">выйти</a></li>
              </ul>
            {% endif %}
          {% endblock %}
        </div>

        <div class="main_content col-8">
          {% if messages %}
          <div class="row">
            <ul class="messages">
              {% for message in messages %}
              <li class="alert alert-{{ message.tags }} alert-dismissable">
                {{ message|safe }}
                <a href="#" class="close" data-dismiss="alert">x</a>
              </li>
              {% endfor %}
            </ul>
          </div>
          {% endif %}
          {% block main_content %}
          {% endblock %}
        </div>

      </div>
    </div>
  </body>
</html>