New/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.base, name='base'),
]

mySite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('Index.urls')),
    path('Index/', include('Index.urls')),
    path("zapis/", include("zapis.urls", namespace="zapis")),
    path("accounts/", include("accounts.urls")),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

zapis/urls.py
from django.urls import path

from . import views

app_name = "zapis"

urlpatterns = [
    path("list/", views.zapis_by_tag, name="list"),
    path("list/tag/<slug:tag_slug>", views.zapis_by_tag, name="list_by_tag"),
    path("create/", views.ZapisCreateView.as_view(), name="create"),
    path("add-zapis/", views.add_zapis, name="api-add-zapis"),
    path("complete/<int:uid>", views.complete_zapis, name="complete"),
    path("delete/<int:uid>", views.delete_zapis, name="delete"),
    path("details/<int:pk>", views.ZapisDetailsView.as_view(), name="details"),
    path("edit/<int:pk>", views.ZapisEditView.as_view(), name="edit"),
    path("export/", views.ZapisExportView.as_view(), name="export"),
]

zapis/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager


class TodoItem(models.Model):
    objects = None
    PRIORITY_HIGH = 1
    PRIORITY_MEDIUM = 2
    PRIORITY_LOW = 3

    PRIORITY_CHOICES = [
        (PRIORITY_HIGH, "Массаж"),
        (PRIORITY_MEDIUM, "СПА"),
        (PRIORITY_LOW, "Медитация"),
    ]

    description = models.CharField(max_length=64)
    is_completed = models.BooleanField("выполнено", default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="zapis")
    priority = models.IntegerField(
        "Приоритет", choices=PRIORITY_CHOICES, default=PRIORITY_MEDIUM
    )

    tags = TaggableManager()

    def __str__(self):
        return self.description.lower()

    class Meta:
        ordering = ("-created",)

    def get_absolute_url(self):
        return reverse("zapis:details", args=[self.pk])

zapis/forms.py
from django import forms
from zapis.models import TodoItem


class AddTaskForm(forms.Form):
    description = forms.CharField(max_length=64, label="")


class TodoItemForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ("description", "priority", "tags")
        labels = {"description": "Описание", "priority": "", "tags": "тэги"}


class TodoItemExportForm(forms.Form):
    prio_high = forms.BooleanField(
        label="массаж", initial=True, required=False
    )
    prio_med = forms.BooleanField(
        label="спа", initial=True, required=False
    )
    prio_low = forms.BooleanField(
        label="медитация", initial=False, required=False
    )

zapis/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from zapis.forms import AddTaskForm, TodoItemExportForm, TodoItemForm
from zapis.models import TodoItem
from django.shortcuts import redirect, render, get_object_or_404
from taggit.models import Tag


class ZapisDetailsView(DetailView):
    model = TodoItem
    template_name = 'zapis/details.html'



@login_required


def complete_zapis(request, uid):
    t = TodoItem.objects.get(id=uid)
    t.is_completed = True
    t.save()
    return HttpResponse("OK")


def add_zapis(request):
    if request.method == "POST":
        desc = request.POST["description"]
        t = TodoItem(description=desc)
        t.save()
    return redirect(reverse("zapis:list"))


def delete_zapis(request, uid):
    t = TodoItem.objects.get(id=uid)
    t.delete()
    return redirect(reverse("zapis:list"))


class ZapisListView(LoginRequiredMixin, ListView):
    model = TodoItem
    context_object_name = "zapis"
    template_name = "zapis/list.html"

    def get_queryset(self):
        u = self.request.user
        qs = super().get_queryset()
        return qs.filter(owner=u)



    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_zapis = self.get_queryset()
        tags = []
        for t in user_zapis:
            tags.append(list(t.tags.all()))

        def filter_tags(tags_by_task):
            t = []
            for tags in tags_by_task:
                for tag in tags:
                    if tag not in t:
                        t.append(tag)
            return t

        context['tags'] = filter_tags(tags)
        return context


class ZapisCreateView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        form = TodoItemForm(request.POST)
        if form.is_valid():
            new_zapis = form.save(commit=False)
            new_zapis.owner = request.user
            new_zapis.save()
            return redirect(reverse("zapis:list"))

        return render(request, "zapis/create.html", {"form": form})

    def get(self, request, *args, **kwargs):
        form = TodoItemForm()
        return render(request, "zapis/create.html", {"form": form})


class ZapisEditView(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        t = TodoItem.objects.get(id=pk)
        form = TodoItemForm(request.POST, instance=t)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.owner = request.user
            new_task.save()
            form.save_m2m()
            return redirect(reverse("zapis:list"))

        return render(request, "zapis/edit.html", {"form": form})

    def get(self, request, pk, *args, **kwargs):
        t = TodoItem.objects.get(id=pk)
        form = TodoItemForm(instance=t)
        return render(request, "zapis/edit.html", {"form": form, "zapis": t})



class ZapisExportView(LoginRequiredMixin, View):
    def generate_body(self, user, priorities):
        q = Q()
        if priorities["prio_high"]:
            q = q | Q(priority=TodoItem.PRIORITY_HIGH)
        if priorities["prio_med"]:
            q = q | Q(priority=TodoItem.PRIORITY_MEDIUM)
        if priorities["prio_low"]:
            q = q | Q(priority=TodoItem.PRIORITY_LOW)
        zapis = TodoItem.objects.filter(owner=user).filter(q).all()

        body = "Ваши записи и процедуры:\n"
        for t in list(zapis):
            if t.is_completed:
                body += f"[x] {t.description} ({t.get_priority_display()})\n"
            else:
                body += f"[ ] {t.description} ({t.get_priority_display()})\n"

        return body

    def post(self, request, *args, **kwargs):
        form = TodoItemExportForm(request.POST)
        if form.is_valid():
            email = request.user.email
            body = self.generate_body(request.user, form.cleaned_data)
            send_mail("Записи", body, settings.EMAIL_HOST_USER, [email])
            messages.success(request, "Записи были отправлены на почту %s" % email)
        else:
            messages.error(request, "Что-то пошло не так, попробуйте ещё раз")
        return redirect(reverse("zapis:list"))

    def get(self, request, *args, **kwargs):
        form = TodoItemExportForm()
        return render(request, "zapis/export.html", {"form": form})


def zapis_by_tag(request, tag_slug=None):
    u = request.user
    zapis = TodoItem.objects.filter(owner=u).all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        zapis = zapis.filter(tags__in=[tag])

    all_tags = []
    for t in zapis:
        all_tags.append(list(t.tags.all()))

    def filter_tags(tags_by_zapis):
        t = []
        for tags in tags_by_zapis:
            for tag in tags:
                if tag not in t:
                    t.append(tag)
        return t

    all_tags = filter_tags(all_tags)

    return render(
        request,
        "zapis/list.html",
        {"tag": tag, "zapis": zapis, "all_tags": all_tags},
    )

zapis/templates/zapis/create.html
{% extends "home.html" %}
{% load static %}

{% block title %}Сделать запись{% endblock %}

{% block main_content %}
  <h1>Сделать запись</h1>
  <form action="."  method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><button class="add" type="submit">Добавить</button></p>
  </form>
{% endblock %}

zapis/templates/zapis/details.html
{% extends "home.html" %}
{% block title %}Запись {{ object.id }}{% endblock %}

{% block main_content %}
<h1 xmlns:zapis="http://www.w3.org/1999/xhtml" xmlns:zapis="http://www.w3.org/1999/xhtml">Запись</h1>
  <p><b>Процедура</b>: {{ object }}</p>
  <ul>
    <li>
      {{ object.is_completed|yesno:"Выполнено,Не выполнено" }}
    </li>
    <li><i class="far fa-calendar-alt"></i>&nbsp;Создана: {{ object.created|date:"Y-b-d H:i" }}</li>
    <li><i class="far fa-clock"></i>&nbsp;Последнее изменение: {{ object.updated }}</li>
    <li><i class="far fa-edit"></i>&nbsp;<a href="{% url "zapis:edit" pk=object.pk %}">Место проведения</a></li>
  </ul>
  <i class="fas fa-clipboard-list"></i>&nbsp;<a href="{% url "zapis:list" %}">Назад к списку</a>
{% endblock %}

zapis/templates/zapis/edit.html
{% extends "home.html" %}
{% load static %}

{% block title %}Изменить задачу{% endblock %}

{% block main_content %}
<h1 xmlns:zapis="http://www.w3.org/1999/xhtml" xmlns:zapis="http://www.w3.org/1999/xhtml">Поменять задачу</h1>
  <form action="{% url "zapis:edit" zapis.pk %}" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><button class="add" type="submit">Сохранить</button></p>
  </form>
{% endblock %}

zapis/templates/zapis/export.html
{% extends "home.html" %}

{% block title %}Экспорт{% endblock %}

{% block main_content %}
  <h1>Экспорт записей</h1>
  <p>На вашу почту придёт емейл с записями. Уточните список.</p>
  <form action="." method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><button class="add" type="submit">Жмяк</button></p>
  </form>
{% endblock %}

zapis/templates/zapis/list.html
{% extends "home.html" %}
{% load static %}

{% block title %}Задачи на день{% endblock %}

{% block extra_head %}
<script src="{% static 'js/script.js' %}" xmlns:zapis="http://www.w3.org/1999/xhtml"></script>
{% endblock %}

{% block main_content %}
  {% if tag %}
  <h1>Текущие задачи с тэгом "{{ tag.name }}"</h1>
  {% else %}
  <h1>Все текущие задачи</h1>
  {% endif %}


  <p><i class="fa fa-download"></i>&nbsp;<a href="{% url "zapis:export" %}">экспорт</a></p>
  {% for t in all_tags %}
    {% if forloop.first %}<ul class="list-inline">
        <li class="list-inline-item">тэги:</li>
    {% endif %}
    <li class="list-inline-item">
      <a href="{% url "zapis:list_by_tag" t.slug %}">
      {% if t.pk == tag.pk %}
        <span class="badge badge-success">{{ t.name }}</span>
      {% else %}
        <span class="badge badge-info">{{ t.name }}</span>
      {% endif %}
      </a>
    </li>
    {% if forloop.last %}</ul>{% endif %}
  {% endfor %}

  <hr/>
  <ul id="todo-list">
  {% for zapis in zapis %}
    {% if task.is_completed %}
    <li class="completed">
      <input class='checkbox' data-uid={{ zapis.id }} type='checkbox' disabled='disabled' checked='checked'/>
    {% else %}
    <li>
      <input class='checkbox' data-uid={{ zapis.id }} type='checkbox' />
    {% endif %}
      {% if zapis.priority == zapis.PRIORITY_HIGH %}
      <span class="badge badge-pill badge-danger">&nbsp;</span>
      {% elif zapis.priority == zapis.PRIORITY_MEDIUM %}
      <span class="badge badge-pill badge-secondary">&nbsp;</span>
      {% elif zapis.priority == zapis.PRIORITY_LOW %}
      <span class="badge badge-pill badge-success">&nbsp;</span>
      {% endif %}
      <a href={% url "zapis:details" zapis.id %}>{{ zapis }}</a>
      <a class="remove" href={% url "zapis:delete" zapis.id %}>X</a>
      <hr/>
    </li>
  {% endfor %}
  </ul>
{% endblock %} )